Removing Sample V1 code
ONSdigital/rm-collection-exercise-service pull request #266
Opened 2021-08-31 13:28 UTC by warrenbailey

# What and why?

# How to test?

# Trello

2021-09-01 08:07 UTC, warrenbailey commented
/deploy baileyw

2021-09-01 09:10 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 09:13 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 13:47 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 14:47 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 14:54 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 15:37 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 15:43 UTC, warrenbailey commented
/deploy baileyw

2021-09-02 15:55 UTC, warrenbailey commented
/deploy baileyw

2021-09-03 14:30 UTC, warrenbailey commented
/deploy baileyw

2021-09-03 15:01 UTC, warrenbailey commented
/deploy bailey

2021-09-03 15:03 UTC, warrenbailey commented
/deploy baileyw

2021-09-06 07:05 UTC, warrenbailey commented
/deploy baileyw

2021-09-06 07:31 UTC, warrenbailey commented
/deploy baileyw

2021-09-09 15:54 UTC, warrenbailey commented on src/main/java/uk/gov/ons/ctp/response/collection/exercise/endpoint/CollectionExerciseEndpoint.java
> -    // If we are in the failed validation state, then there should be validation error so go look
this needs to go back in now

2021-09-09 16:05 UTC, warrenbailey commented
/deploy baileyw

2021-09-10 10:34 UTC, warrenbailey commented
/deploy baileyw

2021-09-10 11:39 UTC, warrenbailey commented
/deploy baileyw

2021-09-13 08:45 UTC, warrenbailey commented
/deploy baileyw

2021-09-15 13:07 UTC, insacuri commented
```
request-collection-instruments: /collection-instrument-api/1.0.2/collectioninstrument
```
in the application.yml and the associated code config needs to be removed now that nothing uses it

2021-09-15 14:47 UTC, insacuri requested changes
One small change but this is looking good

2021-09-15 15:02 UTC, insacuri commented
/deploy manna

2021-09-16 08:17 UTC, warrenbailey commented
/deploy baileyw

2021-09-16 09:02 UTC, insacuri approved these changes

2021-09-16 09:24 UTC, merged