RAS-872: Extend EQ launch claims to include sds_dataset_id if required for the form_type
ONSdigital/rm-collection-exercise-service pull request #318
Opened 2023-09-07 07:05 UTC by SteveScorfield

# What and why?

# How to test?

# Jira
https://jira.ons.gov.uk/browse/RAS-872

2023-09-07 07:29 UTC, SteveScorfield commented
/deploy scorfs

2023-09-07 07:53 UTC, SteveScorfield commented
/deploy scorfs

2023-09-07 08:17 UTC, SteveScorfield commented
/deploy scorfs

2023-09-11 07:32 UTC, SteveScorfield commented
/deploy scorfs

2023-09-12 10:39 UTC, SteveScorfield commented
/deploy scorfs

2023-09-12 11:31 UTC, SteveScorfield commented
/deploy scorfs

2023-09-12 12:05 UTC, SteveScorfield commented
/deploy scorfs

2023-09-12 12:17 UTC, SteveScorfield commented
/deploy scorfs

2023-09-14 11:47 UTC, SteveScorfield commented
/deploy scorfs

2023-09-14 14:55 UTC, JacobHarrisonONS requested changes

2023-09-14 14:55 UTC, JacobHarrisonONS commented on src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SupplementaryDatasetService.java
> +  public SupplementaryDatasetEntity findSupplementaryDataset(int exercise_pk) {
rename to exercise_pk to exercisePk

2023-09-14 14:55 UTC, JacobHarrisonONS commented on src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/CollectionExercise.java
> +  //  @OneToOne(optional = true) is true by default
delete commented code

2023-09-14 15:03 UTC, JacobHarrisonONS commented
/deploy harrisonj

2023-09-14 15:05 UTC, SteveScorfield commented on src/main/java/uk/gov/ons/ctp/response/collection/exercise/domain/CollectionExercise.java
> +  //  @OneToOne(optional = true) is true by default
Done

2023-09-14 15:07 UTC, SteveScorfield commented on src/main/java/uk/gov/ons/ctp/response/collection/exercise/service/SupplementaryDatasetService.java
> +  public SupplementaryDatasetEntity findSupplementaryDataset(int exercise_pk) {
Done

2023-09-14 16:54 UTC, SteveScorfield commented
/deploy scorfs

2023-09-15 10:33 UTC, anwilkie commented
/deploy wilkia

2023-09-18 08:39 UTC, SteveScorfield commented
/deploy scorfs

2023-09-18 09:38 UTC, SteveScorfield commented
/deploy scorfs

2023-09-18 12:21 UTC, JacobHarrisonONS commented
/deploy harrisonj

2023-09-19 09:12 UTC, merged