RAS-930 Reduce collection exercise logging level to info
ONSdigital/rm-collection-exercise-service pull request #325
Opened 2023-11-20 13:08 UTC by arroyoAle

# What and why?
Updating the logging level from debug to info
# How to test?
deploy to you environment and run the acceptance tests, make sure that no `debug` level logs appear in the collection exercise logs
# Jira
https://jira.ons.gov.uk/browse/RAS-930

2023-11-21 09:34 UTC, LJBabbage requested changes
There are a couple of log line in there that need upping

"Event is not actionable, setting to COMPLETED state", "Problem loading fixture {} reason {}"

A couple I am on the fence with i.e "Deleting collection exercise event id, event tag". I am not bothered about getting DTOs or hitting end points etc, but deleting things I am a bit more interested to see them in the logs, at a stretch an important creation as well.

2023-11-21 11:50 UTC, arroyoAle commented
> There are a couple of log line in there that need upping
> 
> "Event is not actionable, setting to COMPLETED state", "Problem loading fixture {} reason {}"
> 
> A couple I am on the fence with i.e "Deleting collection exercise event id, event tag". I am not bothered about getting DTOs or hitting end points etc, but deleting things I am a bit more interested to see them in the logs, at a stretch an important creation as well.

I've updated some of the debug logs, mostly to info, but the ones which are around problems were elevated to warn (they're also in the test directory)

2023-11-22 09:30 UTC, LJBabbage approved these changes

2023-11-22 18:36 UTC, mfcrocker approved these changes

2023-11-23 09:15 UTC, merged